### PR TITLE
Fix memory leak.

### LINKED ISSUE #911: "do_mix" seems to leak memory
I tested ``do_mix`` using the following script.
https://github.com/rimms/misc/tree/master/do_mix_loop

The result is the following graph:

graph

### PR DESCRIPTION
**Pull request by gwtnb**
Fixed #911.
zoo_get_children() returns allocated memory implicitly.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Code Review: @gintenlabo

File: jubatus/server/common/zk.cpp [hunk 1]
```diff
@@ -335,18 +335,60 @@ bool zk::list(const string& path, vector<string>& out) {
   return list_(path, out);
 }
 
+namespace {
+
+class string_vector_holder {
```
Comment (gintenlabo) [inline jubatus/server/common/zk.cpp]: This class should be noncopyable.

**Comment by rimms** [comment]
I tested this patch with the test script.

graph_after

This patch is too effective to solve the problem of #911.
But, It seems to leak memory yet. : (

I will marge this patch.
(But, I will not close #911.)
